version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -Dmaven.test.skip=true
    post_build:
      commands:
        - echo Build Completed.
artifacts:
    base-directory: tjm-web-app/target
    files:
      - tjm-content-management-app-server.jar
    discard-paths: yes
