spring.application.name=tjm-web-app

# Set the logging level for the root logger
logging.level.root=INFO

# Set the logging level for a specific package
logging.level.com.example.myapp=DEBUG

# Configure logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Enable color coding in console output
spring.output.ansi.enabled=ALWAYS

logging.file.path=logs/
logging.file.name=logs/application.log 
